#!/usr/bin/python2
from __future__ import print_function

import requests
import sys
import time
import random

import click

from utility import get_geolocation, get_initial_url
from output import (
    cyan_text, red_text, green_text, yellow_text, magenta_text,
    format_ip_from_parts, info_banner, title_banner,
)


class CapturedHttp(object):
    def __init__(self, ipaddr, response):
        self.ipaddr = ipaddr
        self.status_code = response.status_code
        try:
            self.server = response.headers['Server']
        except KeyError:
            self.server = "Not Available"
        self.cookies = response.cookies
        self.headers = response.headers

    def __str__(self):
        try:
            outstr = "[{:17s}] <{}>  ({})".format(
                self.ipaddr, self.status_code, self.server)
        except Exception as e:
            outstr = "An exception occurred: {}".format(e)
        return outstr


DEFAULT_TIMEOUT = 4
DEFAULT_PORT = 80
DEFAULT_PORT_LIST = [80, 8080]
timeout_used = DEFAULT_TIMEOUT


def get_auth_details(headers, verbose=False):
    try:
        auth = headers['www-authenticate']
    except KeyError as ke:
        if verbose:
            print("No Auth Header: ", ke)
        return (None, None)

    auth_type, realm_parts = auth.split(' ', 1)
    realm = realm_parts.split('=', 1)[1]
    return auth_type, realm


@click.command()
@click.argument('network', type=str)
@click.option('--timeout', '-t', 'timeout',
              type=int, default=DEFAULT_TIMEOUT,
              help=("Specify connection timeout value in seconds. "
                    "Default: {} seconds".format(DEFAULT_TIMEOUT)))
@click.option('--verbose', '-v', 'verbose',
              is_flag=True, default=False,
              help=("Display additional information. Useful for interactive."))
@click.option('--port', '-p', 'scan_port',
              type=int, default=DEFAULT_PORT,
              help=("Specify specific port to connect to. "
                    "Default: {}".format(DEFAULT_PORT)))
def main(network, timeout, verbose, scan_port):
    """
    HTTP Harvester - Rattling doorknobs in your local Class C

    Performs simple connection-based scans, attempting to connect
    to port 80, looking for HTTP servers.

    When a server has been found, the reported Server header is shown.
    """
    hosts_list = []

    target = network
    ip_parts = target.split('.')
    copy_ip = ip_parts
    copy_ip[3] = str(0)

    scanned_set = set()

    # max_time = DEFAULT_TIMEOUT * 254
    total_time = 0

    location = get_geolocation(network)

    print(title_banner("  HTTP Harvest Scan on {}  |  {}{}".format(
          format_ip_from_parts(copy_ip), location, 20 * " ")))

    while len(scanned_set) < 254:
        auth_type = auth_realm = None
        host_byte = random.randint(1, 254)
        if host_byte in scanned_set:
            continue

        status_string = ""
        server = "???"
        country = "???"
        copy_ip[3] = str(host_byte)
        try:
            start_time = time.time()
            print ("{:>16}:{:<5}  |  ".format(
                   format_ip_from_parts(copy_ip),
                   scan_port), end="")
            sys.stdout.flush()
            ip_str = format_ip_from_parts(copy_ip)
            initial_url = get_initial_url(ip_str, port=scan_port)

            r = requests.get(initial_url, timeout=float(timeout))

            try:
                server = r.headers['Server']
            except KeyError:
                pass

            if r.status_code == 200:
                status_string = green_text("{:^5s}".format("OK"))
                country = get_geolocation(format_ip_from_parts(copy_ip))
            elif r.status_code > 400 and r.status_code < 500:
                status_string = yellow_text("{:^5s}".format(
                    str(r.status_code)))
                country = get_geolocation(format_ip_from_parts(copy_ip))
                if r.status_code == 401:
                    auth_type, auth_realm = get_auth_details(r.headers)

            hosts_list.append(
                CapturedHttp(format_ip_from_parts(copy_ip), r)
            )
        except requests.Timeout as e:
            status_string = magenta_text("{:^5s}".format("T.O"))
        except requests.ConnectionError as e:
            status_string = red_text("{:^5s}".format("C.E"))
        except requests.TooManyRedirects as e:
            status_string = cyan_text("{:^5s}".format("R.L"))
        except KeyboardInterrupt as e:
            print("\n\n  ***  Scan Interrupted  *** ", end='')
            print(" {}/254 hosts scanned  ***\n".format(len(scanned_set)))
            sys.exit(1)

        scan_time = time.time() - start_time
        total_time += scan_time

        print("{:5s}  {:>2.2f}s [{:^20}] ({})  {}".format(
            status_string, scan_time, server[:19], country,
            "" if auth_realm is None else auth_realm))

        scanned_set.add(host_byte)

    print("Scan took {:3.1f} minutes".format(total_time / 60))

    print("\nInfo found for {} hosts".format(len(hosts_list)))
    print("".format())


if __name__ == '__main__':
    main()
